# Generated by Django 4.2.5 on 2024-04-19 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0002_rename_user_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='User',
        ),
    ]
