# Generated by Django 4.2.5 on 2024-04-19 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0003_rename_register_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Register',
        ),
    ]
