# Generated by Django 4.2.5 on 2024-04-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0005_signup_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('confirm_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
