# Generated by Django 5.0.3 on 2024-04-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0006_register_delete_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(max_length=100)),
                ('aadharfront', models.ImageField(blank=True, upload_to=None)),
                ('aadharback', models.ImageField(blank=True, upload_to=None)),
                ('email', models.EmailField(max_length=254)),
                ('picture', models.ImageField(blank=True, upload_to=None)),
                ('address', models.CharField(max_length=100)),
                ('schoolname', models.CharField(max_length=100)),
                ('marital', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('college_name', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('sibling', models.CharField(max_length=100)),
                ('friend_name', models.CharField(max_length=100)),
                ('animal_name', models.CharField(max_length=100)),
                ('eat', models.CharField(max_length=100)),
                ('profile_name', models.CharField(max_length=100)),
            ],
        ),
    ]
