# Generated by Django 5.0.3 on 2024-04-25 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0007_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='profile_name',
            new_name='profilename',
        ),
    ]
