# Generated by Django 5.0.3 on 2024-04-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0008_rename_profile_name_question_profilename'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
