# Generated by Django 5.0.3 on 2024-05-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0011_compose'),
    ]

    operations = [
        migrations.AddField(
            model_name='compose',
            name='files',
            field=models.FileField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
