# Generated by Django 5.0.3 on 2024-05-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0012_compose_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compose',
            name='files',
            field=models.ImageField(blank=True, upload_to=None),
        ),
    ]
