# Generated by Django 5.0.3 on 2024-05-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0014_alter_compose_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compose',
            name='message',
            field=models.TextField(),
        ),
    ]
