# Generated by Django 5.0.3 on 2024-05-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0015_alter_compose_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('files', models.FileField(upload_to='media')),
            ],
        ),
        migrations.DeleteModel(
            name='Compose',
        ),
    ]
