# Generated by Django 5.0.3 on 2024-05-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0016_cmail_delete_compose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmail',
            name='files',
        ),
        migrations.AddField(
            model_name='cmail',
            name='doc',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
