# Generated by Django 5.0.3 on 2024-05-08 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0017_remove_cmail_files_cmail_doc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cmail',
            new_name='Copmail',
        ),
    ]
