# Generated by Django 5.0.3 on 2024-05-08 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0018_rename_cmail_copmail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copmail',
            old_name='doc',
            new_name='file_field',
        ),
    ]
