# Generated by Django 5.0.3 on 2024-05-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0019_rename_doc_copmail_file_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
