# Generated by Django 5.0.3 on 2024-05-08 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0020_register_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='image',
        ),
    ]
