# Generated by Django 5.0.3 on 2024-05-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0021_remove_register_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='file_field',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
