# Generated by Django 5.0.3 on 2024-05-10 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0022_register_file_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='file_field',
            new_name='doc',
        ),
    ]
