# Generated by Django 5.0.3 on 2024-05-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0023_rename_file_field_register_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='doc',
        ),
        migrations.AddField(
            model_name='profile',
            name='file_field',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
