# Generated by Django 5.0.3 on 2024-05-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0024_remove_register_doc_profile_file_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='file_field',
        ),
        migrations.AddField(
            model_name='register',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
