# Generated by Django 5.0.3 on 2024-05-10 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0026_alter_register_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='profile_image',
        ),
    ]
