# Generated by Django 5.0.3 on 2024-05-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0027_remove_register_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
