# Generated by Django 5.0.3 on 2024-05-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0028_alter_question_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
