# Generated by Django 5.0.3 on 2024-05-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0029_alter_question_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='picture',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
