# Generated by Django 5.0.3 on 2024-05-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0030_alter_question_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
