# Generated by Django 5.0.3 on 2024-05-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0031_register_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
