# Generated by Django 5.0.3 on 2024-05-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0032_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
        migrations.AlterField(
            model_name='question',
            name='aadharback',
            field=models.FileField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='question',
            name='aadharfront',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
