# Generated by Django 5.0.3 on 2024-05-11 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0033_remove_profile_profile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='profile_image',
        ),
    ]
