# Generated by Django 4.2.6 on 2024-05-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("start", "0034_remove_register_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="picture",
            field=models.ImageField(blank=True, upload_to="media"),
        ),
    ]
