# Generated by Django 4.2.6 on 2024-05-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("start", "0035_alter_question_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="register",
            name="pic",
            field=models.ImageField(blank=True, upload_to="media"),
        ),
    ]
