# Generated by Django 4.2.6 on 2024-05-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("start", "0037_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrashCopmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_id", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("file_field", models.FileField(blank=True, upload_to="media")),
                ("deleted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
