# Generated by Django 4.2.6 on 2024-05-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("start", "0038_trashcopmail"),
    ]

    operations = [
        migrations.RemoveField(model_name="register", name="pic",),
    ]
