# Generated by Django 4.2.6 on 2024-05-18 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("start", "0039_remove_register_pic"),
    ]

    operations = [
        migrations.RenameModel(old_name="TrashCopmail", new_name="Trashmail",),
    ]
