# Generated by Django 4.2.6 on 2024-05-18 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("start", "0040_rename_trashcopmail_trashmail"),
    ]

    operations = [
        migrations.RenameModel(old_name="Trashmail", new_name="TrashCopmail",),
    ]
