# Generated by Django 4.2.6 on 2024-05-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("start", "0041_rename_trashmail_trashcopmail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="copmail",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
