# Generated by Django 4.2.6 on 2024-05-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("start", "0042_alter_copmail_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="copmail",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
