# Generated by Django 5.0.3 on 2025-04-30 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("start", "0044_room_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="online",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="Room",
        ),
    ]
